apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Allow 1 extra pod to spin up during deployment
      maxUnavailable: 0  # Guarantee NO existing pods terminate until the new pod is healthy
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        # Notice this points to YOUR Docker Hub namespace!
        image: kirandevraaj/order-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "v1.0.0"
        # If this probe fails, K8s restarts the container automatically
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        # If this probe fails during rollout, K8s halts the deployment!
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3