apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  namespace: production
  labels:
    app: order-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      serviceAccountName: jenkins-deployer-sa
      containers:
      - name: order-api
        image: kirandevraaj/order-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "v1.0.0"
        # -- ADD THIS RESOURCES BLOCK TO SATISFY TERRAFORM QUOTA --
        resources:
          requests:
            cpu: "100m"      # Request 0.1 CPU core
            memory: "128Mi"  # Request 128 MB Memory
          limits:
            cpu: "500m"      # Cap at 0.5 CPU core
            memory: "256Mi"  # Cap at 256 MB Memory
        # ---------------------------------------------------------
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3