apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: production      # Routes traffic inside the production namespace
spec:
  type: NodePort
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30050